### ISSUE TITLE
Zero-crossings

### ISSUE THREAD

**Issue by DominiqueMakowski** [raphaelvallat/antropy#17]
Hi Raph, 

Was doing some cross-checking and I have a quick question to disperse a doubt in my mind regarding the counting of the number of inversions:

https://github.com/raphaelvallat/antropy/blob/88fea895dc464fd075f634ac81f2ae4f46b60cac/antropy/entropy.py#L908

Shouldn't it be: `np.diff(np.signbit(np.diff(` here? I.e., counting the changes in sign of the consecutive differences, rather than the difference of the sign of the consecutive samples 🤔

**Comment by raphaelvallat** [comment]
Hi @DominiqueMakowski!

You mean using `np.diff(np.signbit(x), n=2).sum()` instead of `np.diff(np.signbit(x)).sum()`, correct?

Taking a sine wave example, I think that the current method implemented in AntroPy is correct:

```python
import numpy as np
import matplotlib.pyplot as plt
sf, f, dur = 100, 1, 4
N = sf * dur # Total number of discrete samples
t = np.arange(N) / sf # Time vector
x = np.sin(2 * np.pi * f * t)
plt.plot(t, x)
plt.xlim(t[0], t[-1])
plt.axhline(0);
```

![image](https://user-images.githubusercontent.com/25703792/164758431-e534cdbe-be0a-4b37-9ef2-c113a54f8f1c.png)

There are 7 zero-crossings in `x`.

```python
>>> def nzc(x, n):
>>>   return np.diff(np.signbit(x), n=n).sum()
>>> nzc(x, n=1), nzc(x, n=2)
(7, 14)
```

The `n=1` method (default) gives the correct answer. The double differentiation leads to twice the expected number of zero-crossings.

Thanks,
Raphael

**Comment by DominiqueMakowski** [comment]
Ah sorry yes I must have been asleep and missed one step ^^ (I was looking at [here](https://github.com/raphaelvallat/antropy/blob/88fea895dc464fd075f634ac81f2ae4f46b60cac/antropy/fractal.py#L97) but I didn't see the that the `diff` was inside here) thanks!
