### ISSUE TITLE
numba jit needs explicit nopython=True

### ISSUE THREAD

**Issue by fingoldo** [raphaelvallat/antropy#29]
C:\ProgramData\Anaconda3\lib\site-packages\antropy\fractal.py:197: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  @jit((types.Array(types.float64, 1, "C", readonly=True), types.int32))

**Comment by raphaelvallat** [comment]
Hi @fingoldo ,

This has been fixed in https://github.com/raphaelvallat/antropy/commit/e76a8c7428aba316e5e8c0f31f5e6257704c992c and is available in the `master` branch. However, I have not yet released a new version of antropy that integrate these changes. As an immediate solution, I suggest that you install git clone antropy to benefit from the latest changes in `master`.

**Comment by raphaelvallat** [comment]
I'll release a new version on PyPi next week or sooner.

**Comment by raphaelvallat** [comment]
https://github.com/raphaelvallat/antropy/releases/tag/v0.1.6
