### ISSUE TITLE
The most "generic" entropy measure

### ISSUE THREAD

**Issue by antelk** [raphaelvallat/antropy#4]
Hi,

Is there any review paper available that overviews the performance of different entropy measures which are implemented in this library for the actual electrophysiological data?
Also, what would be the measure with the smallest number of non-optional parameters that is also guaranteed to work in most cases?

Thank you!

**Comment by raphaelvallat** [comment]
Hi @antelk,

> Is there any review paper available that overviews the performance of different entropy measures which are implemented in this library for the actual electrophysiological data?

I am not aware of any papers that have explicitly compared all (or most of) the metrics implemented in antropy, but the following references might help:

- https://ieeexplore.ieee.org/abstract/document/1634501
- https://www.sciencedirect.com/science/article/pii/S1087079217300187
- https://pubmed.ncbi.nlm.nih.gov/12005759/

Also please check this notebook in which I calculate [the correlation](https://github.com/raphaelvallat/antropy/blob/master/notebooks/complexity_corr_noise.ipynb) between all these metrics. As you can see, they are all highly correlated.

> Also, what would be the measure with the smallest number of non-optional parameters that is also guaranteed to work in most cases?

That's a good question, and I'm not sure there's a perfect answer. I personally like to use the permutation entropy for EEG data (with order=3 and delay=1) because it is fast, straightforward, and robust to outliers (based on rank). The sample entropy is also a good default choice. The spectral entropy is easy to understand and simple, but highly dependent on the choice of parameters for calculating the power spectrum.

Thanks,
Raphael

**Comment by antelk** [comment]
@raphaelvallat, thank you for such a comprehensive and informative response.

I actually read the last paper by Bandt and Pope,  Phys Rev Lett 2002.
While looking at your code, I noticed that you [cited this paper](https://github.com/raphaelvallat/antropy/blob/master/antropy/entropy.py#L61-L63) and decided to give it a go. However, there are a few more papers that I am aware of that make very similar conclusions while using a completely different methodology.

> Also please check this notebook in which I calculate the correlation between all these metrics. As you can see, they are all highly correlated.

This is awesome! Motivated by these results, I decided to reproduce them on the membrane potential traces obtained by solving the Hodgkin-Huxley system of equations. Do you think it’s a good idea to suggest a pull request to have another example on “real” electrophysiology data?

Thank you again!
Ante

**Comment by raphaelvallat** [comment]
That is a great idea, please do submit a PR!
